import { useEffect, useState } from "react";
import { BarChart3, BookOpen, GraduationCap, Users, ClipboardCheck, FileText, Clock, TrendingUp } from "lucide-react";
import { StatCard } from "../../components/StatCard";
import { ChartCard } from "../../components/ChartCard";
import { getDashboard } from "../../services/principalServiceApi";
import type { PrincipalDashboardData } from "../../services/principalServiceApi";

function SimpleBar({ value, max, label, color = "bg-[#36ADAA]" }: { value: number; max: number; label: string; color?: string }) {
  const pct = max > 0 ? (value / max) * 100 : 0;
  return (
    <div className="flex items-center gap-3">
      <span className="w-28 truncate text-sm font-semibold text-slate-600">{label}</span>
      <div className="flex-1 rounded-full bg-slate-100 h-3 overflow-hidden">
        <div
          className={`h-full rounded-full ${color} transition-all duration-700 ease-out`}
          style={{ width: `${pct}%` }}
        />
      </div>
      <span className="w-10 text-right text-sm font-bold text-slate-800">{value}</span>
    </div>
  );
}

function roleTone(role: string) {
  if (role === "Principal") return "bg-amber-50 text-amber-700";
  if (role === "Student") return "bg-sky-50 text-sky-700";
  return "bg-emerald-50 text-emerald-700";
}

export function PrincipalDashboard() {
  const [data, setData] = useState<PrincipalDashboardData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getDashboard()
      .then(setData)
      .catch(() => setData(null))
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div className="flex items-center justify-center py-32">
        <div className="flex items-center gap-3 rounded-2xl bg-white/90 px-6 py-4 shadow-lg">
          <div className="h-5 w-5 animate-spin rounded-full border-2 border-[#36ADAA] border-t-transparent" />
          <span className="text-sm font-semibold text-slate-600">Loading dashboard...</span>
        </div>
      </div>
    );
  }

  if (!data) {
    return (
      <div className="flex items-center justify-center py-32">
        <div className="rounded-2xl bg-white/90 px-8 py-6 shadow-lg text-center">
          <p className="text-lg font-bold text-slate-800">Unable to load dashboard data.</p>
          <p className="mt-2 text-sm text-slate-500">Please try again later.</p>
        </div>
      </div>
    );
  }

  const hasAnalyticsData =
    data.totalTeachers > 0 ||
    data.totalClasses > 0 ||
    data.totalStudents > 0 ||
    data.lessonPlansGenerated > 0 ||
    data.evaluationsCompleted > 0 ||
    data.lessonPlansBySubject.length > 0 ||
    data.evaluationPerformance.length > 0 ||
    data.teacherActivity.length > 0 ||
    data.monthlyProgress.some((item) => item.value > 0) ||
    data.recentActivity.length > 0;

  if (!hasAnalyticsData) {
    return (
      <div className="flex items-center justify-center py-32">
        <div className="rounded-2xl bg-white/90 px-8 py-6 shadow-lg text-center">
          <BarChart3 className="mx-auto h-10 w-10 text-slate-300" />
          <p className="mt-4 text-lg font-bold text-slate-800">No real dashboard data yet</p>
          <p className="mt-2 text-sm text-slate-500">The principal dashboard will populate automatically once teachers and students start creating records in the system.</p>
        </div>
      </div>
    );
  }

  const maxLessonPlan = Math.max(...data.lessonPlansBySubject.map((s) => s.count), 1);
  const maxEvalScore = 100;

  return (
    <div className="space-y-6 animate-[fadeInUp_0.4s_ease-out]">
      <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-5">
        <StatCard label="Total Teachers" value={String(data.totalTeachers)} detail="Faculty monitored in the LMS" icon={Users} />
        <StatCard label="Total Classes" value={String(data.totalClasses)} detail="Active classrooms" icon={GraduationCap} />
        <StatCard label="Total Students" value={String(data.totalStudents)} detail="Enrolled across all classes" icon={BookOpen} />
        <StatCard label="Lesson Plans" value={String(data.lessonPlansGenerated)} detail="Generated by teachers" icon={FileText} />
        <StatCard label="Evaluations" value={String(data.evaluationsCompleted)} detail="Completed assessments" icon={ClipboardCheck} />
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <ChartCard title="Lesson Plans by Subject" subtitle="Count of lesson plans generated per subject" icon={<FileText className="h-5 w-5" />}>
          <div className="space-y-3">
            {data.lessonPlansBySubject.map((item) => (
              <SimpleBar key={item.subject} label={item.subject} value={item.count} max={maxLessonPlan} />
            ))}
          </div>
        </ChartCard>

        <ChartCard title="Evaluation Performance" subtitle="Average score by class" icon={<BarChart3 className="h-5 w-5" />}>
          <div className="space-y-3">
            {data.evaluationPerformance.map((item) => (
              <SimpleBar key={item.label} label={item.label} value={item.score} max={maxEvalScore} color="bg-[#7F64EA]" />
            ))}
          </div>
        </ChartCard>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <ChartCard title="Monthly Progress" subtitle="Overall progress trend" icon={<TrendingUp className="h-5 w-5" />}>
          <div className="flex items-end justify-between gap-2 h-40">
            {data.monthlyProgress.map((m) => (
              <div key={m.month} className="flex flex-1 flex-col items-center gap-2">
                <span className="text-xs font-bold text-[#36ADAA]">{m.value}%</span>
                <div
                  className="w-full rounded-t-lg bg-gradient-to-t from-[#36ADAA] to-[#9FCDD2] transition-all duration-700"
                  style={{ height: `${m.value}%` }}
                />
                <span className="text-[11px] font-semibold text-slate-500">{m.month}</span>
              </div>
            ))}
          </div>
        </ChartCard>
      </div>

      <ChartCard title="Recent Activity" subtitle="Latest role-based activity across the school" icon={<Clock className="h-5 w-5" />}>
        <div className="space-y-2">
          {data.recentActivity.map((activity, idx) => (
            <div key={idx} className="flex items-center justify-between rounded-2xl bg-slate-50/80 px-4 py-3 transition hover:bg-slate-100">
              <div className="flex items-center gap-3 min-w-0">
                <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-[#36ADAA]/10 text-xs font-black text-[#36ADAA]">
                  {activity.teacherName.charAt(0)}
                </div>
                <div className="min-w-0">
                  <div className="flex items-center gap-2">
                    <span className={`rounded-full px-2.5 py-0.5 text-[10px] font-black uppercase tracking-[0.16em] ${roleTone(activity.role)}`}>
                      {activity.role}
                    </span>
                    <span className="text-sm font-bold text-slate-800">{activity.teacherName}</span>
                  </div>
                  <div className="text-sm text-slate-600">{activity.action}</div>
                </div>
              </div>
              <span className="shrink-0 ml-3 text-xs font-semibold text-slate-400">{activity.timeAgo}</span>
            </div>
          ))}
        </div>
      </ChartCard>
    </div>
  );
}
